// src/Interface/Web/src/lib/components/ExternalLink.svelte
<script>
	import { discordSdk } from "$lib/discord";

	let {
		href,
        className = undefined,
        target = '_blank',
        children,
        ariaLabel = undefined,
	} = $props();
</script>

{#if discordSdk}
    <button
        class={className ? className + ' cursor-pointer' : 'cursor-pointer'}
        aria-label={ariaLabel}
        type="button"
        onclick={async () => {
            if (discordSdk) {
                await discordSdk.commands.openExternalLink({
                    url: href,
                });
            }
        }}
    >
        {@render children()}
    </button>
{:else}
    <a href={href} target={target} class={className} aria-label={ariaLabel}>
        {@render children()}
    </a>
{/if}

// src/web/components/ExternalLink.tsx
import type { ComponentChildren, HTMLAttributeAnchorTarget } from "preact";

export default function ExternalLink(
  props: {
    href: string;
    clientId: string | null;
    target?: HTMLAttributeAnchorTarget;
    class?: string;
    ariaLabel?: string;
    children: ComponentChildren;
  },
) {
  const className = props.class
    ? props.class + " cursor-pointer"
    : "cursor-pointer";
  let href = props.href;

  if (!props.clientId) {
    href = `/external?to=${encodeURIComponent(href)}`;
  }

  return (
    <a
      href={href}
      target={props.target ?? "_blank"}
      class={className}
      aria-label={props.ariaLabel}
    >
      {props.children}
    </a>
  );
}
